name: autofix.ci # needed to securely identify the workflow

on: [push, pull_request]

permissions:
  contents: read

jobs:
  autofix:
    name: Autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7

      - name: Setup aube
        uses: endevco/aube-action@v1
        with:
          node-version: auto
          run-install: true

      - name: Migrate Biome schema
        run: aubx biome migrate --write

      - name: Apply Biome fixes
        run: aubr lint:fix

      - name: Generate PWA icons
        run: aubr generate-icons

      - name: Update current year in _redirects
        run: node scripts/update-year.mts

      - name: Run autofix.ci
        uses: autofix-ci/action@v1
        with:
          commit-message: "refactor: apply automatic fixes"
