name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup aube
        uses: jdx/aube-action@v1
        with:
          node-version: auto
          run-install: true
      - name: Build
        run: aubr build
  type-check:
    name: Type check

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup aube
        uses: jdx/aube-action@v1
        with:
          node-version: auto
          run-install: true
      - name: Run Astro check
        run: aubr check
  lint:
    name: Lint

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup aube
        uses: jdx/aube-action@v1
        with:
          node-version: auto
          run-install: true
      - name: Lint
        run: aubr lint
