name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Build
        run: pnpm build
  type-check:
    name: Type check

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Run Astro check
        run: pnpm check
  lint:
    name: Lint

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Lint
        run: pnpm lint
